# TCP node communication setup
Master_IP: "169.254.105.68"
Master_port: 8888
Local_IP: "169.254.254.89"

Command_topic: "/fpga/command"
Publish_topic: "/fpga/state"

# function mode : "SET_THETA, TCP_SLAVE, CUSTOM_1, CUSTOM_2, CUSTOM_3"
Behavior_mode: "SET_THETA"

# Interrupt Setup, Triggered By FPGA IRQ
# IRQ 0
# Loop Period (type int) of the main loop, where controllers were implemented
MainLoop_period_us: 1000
# IRQ 1
# Loop Period (type int) of the loop handling CAN transceiving, at least 1000 us
CanLoop_period_us: 1000

# CAN Bus timeout
CAN_Timeout_us: 500

# MOD A
LF_Module:
  Enable: 1
  CAN_PORT: "MOD1CAN0"
  Motor_F:
    FW_Version: 3
    CAN_ID: 8
    KP: 50
    KI: 0
    KD: 1.5
    Torque_Feedfoward: 0
  Motor_H:
    FW_Version: 3
    CAN_ID: 9
    KP: 50
    KI: 0
    KD: 1.5
    Torque_Feedfoward: 0

# MOD B
RF_Module:
  Enable: 1
  CAN_PORT: "MOD1CAN1"
  Motor_F:
    FW_Version: 3
    CAN_ID: 11
    KP: 50
    KI: 0
    KD: 1.5
    Torque_Feedfoward: 0
  Motor_H:
    FW_Version: 3
    CAN_ID: 17
    KP: 50
    KI: 0
    KD: 1.5
    Torque_Feedfoward: 0

# MOD C
RH_Module:
  Enable: 1
  CAN_PORT: "MOD2CAN0"
  Motor_F:
    FW_Version: 3
    CAN_ID: 16
    KP: 50
    KI: 0
    KD: 1.5
    Torque_Feedfoward: 0
  Motor_H:
    FW_Version: 3
    CAN_ID: 15
    KP: 50
    KI: 0
    KD: 1.5
    Torque_Feedfoward: 0

# MOD D
LH_Module:
  Enable: 1
  CAN_PORT: "MOD2CAN1"
  Motor_F:
    FW_Version: 3
    CAN_ID: 14
    KP: 50
    KI: 0
    KD: 1.5
    Torque_Feedfoward: 0
  Motor_H:
    FW_Version: 3
    CAN_ID: 13
    KP: 50
    KI: 0
    KD: 1.5
    Torque_Feedfoward: 0

# ADD USED MODULE IN LIST
Number_of_modules: 4
Modules_list:
  0: LF_Module
  1: RF_Module
  2: RH_Module
  3: LH_Module